name: Azure Deployment Pipeline

on: [push]

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/webapp:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE ./app
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push Docker image
        run: docker push $DOCKER_IMAGE

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      
      - name: Azure Login
        run: |
          echo "${{ secrets.AZURE_PASSWORD }}" | az login --username ${{ secrets.AZURE_USERNAME }} --password-stdin
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Terraform Init
        run: terraform init ./terraform
      
      - name: Terraform Apply
        run: terraform apply -auto-approve ./terraform
        env:
          ARM_USE_CLI: true
      
      - name: Get Public IP
        run: |
          IP=$(terraform -chdir=./terraform output -raw public_ip)
          echo "PUBLIC_IP=$IP" >> $GITHUB_ENV
      
      - name: Setup Ansible
        run: sudo apt update && sudo apt install -y ansible
      
      - name: Run Ansible Playbook
        run: |
          ansible-playbook \
            -i "${{ env.PUBLIC_IP }}," \
            -u adminuser \
            --private-key ~/.ssh/azure-container-key \
            -e "docker_image=$DOCKER_IMAGE" \
            ansible/docker.yml
